name = "lighthouse-auditor"
main = "src/index.ts"
compatibility_date = "2025-03-31"

[[kv_namespaces]]
binding = "CACHE"
id = "438a07762a8b47d28aef6dbe510a541f"

[vars]
ALLOWED_ORIGIN = "https://cruciate-hub.github.io"
